backend:
  name: github
  repo: tu_usuario/tu_repo
  branch: main
  auth_type: oauth
  base_url: https://tu-backend.com
  auth_endpoint: auth
  app_id: <tu_github_oauth_app_id>

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "perfiles"
    label: "Perfiles"
    folder: "data/perfiles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "YouTube", name: "youtube", widget: "string", required: false }
      - { label: "Foto de perfil", name: "foto", widget: "image" }

